version: "3.7"

services:
  zucced_api:
    container_name: zucced_api
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: uvicorn --reload zucced_api.asgi:APP --port 8000 --host 0.0.0.0
    environment:
      - POSTGRES_HOST=zucced_db
    depends_on:
      - zucced_db
    ports:
      - 9008:8000
    env_file:
      - .env
    networks:
      - zucced_internal_network
    volumes:
      - .:/home/zucced_api/app/
  zucced_db:
    image: postgres:12-alpine
    container_name: zucced_db
    env_file:
      - .env
    networks:
      - zucced_internal_network

networks:
  zucced_internal_network:
